### DISCUSSION TITLE
Running Portainer on UNRAID (artifactory)

### DISCUSSION THREAD

**Discussion by frakman1** [frakman1/docker-templates#2] [Q&A] [answered]
I was able to get Portainer to run on UNRAID to manage docker containers and most importantly, to run `docker-compose` scripts. 

Get it from Community Applications:

![image](https://user-images.githubusercontent.com/5826484/106374938-9fd77680-6355-11eb-88bb-535978b8bb48.png)

The default template pulls a version of Portainer that doesn't support `docker-compose` versions greater than 2. The workaround was to use a recent beta version with tag `portainerci/portainer:2.1` This is what my docker template looks like:

I just changed these two values:
Repository: `portainerci/portainer:2.1`
Docker Hub URL: `https://registry.hub.docker.com/r/portainerci/portainer/`

![image](https://user-images.githubusercontent.com/5826484/106374993-18d6ce00-6356-11eb-970b-c19171e1d277.png)

This seems to work and allows me to view all my local docker containers on UNRAID:

![image](https://user-images.githubusercontent.com/5826484/106374515-fe025a80-6351-11eb-9246-66f5bd95b494.png)

I then wanted to run a `docker-compose.yml` configuration for artifactory that I know works elsewhere. The file looks like this (modified some host ports in order to avoid conflicts with other containers):

```yaml
version: '3'
services:
 artifactory:
   image: docker.bintray.io/jfrog/artifactory-oss:6.8.3
   user: "${UID}:${GID}"
   container_name: artifactory
   ports:
    - 6081:8081
   volumes:
    - /data/artifactory:/var/opt/jfrog/artifactory
   environment:
    - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx2g -Xss256k -XX:+UseG1GC
   restart: always
   ulimits:
     nproc: 65535
     nofile:
       soft: 32000
       hard: 40000
 nginx:
   image: docker.bintray.io/jfrog/nginx-artifactory-pro:6.8.3
   container_name: nginx
   ports:
    - 680:80
    - 6443:443
   depends_on:
    - artifactory
   links:
    - artifactory
   volumes:
    - /data/nginx:/var/opt/jfrog/nginx
   environment:
    - ART_BASE_URL=http://artifactory:8081/artifactory
    - SSL=true
   restart: always
   ulimits:
     nproc: 65535
     nofile:
       soft: 32000
       hard: 40000
```

The problem is that I get this error about the /data/artifactory folder not existing.

![image](https://user-images.githubusercontent.com/5826484/106374573-8da80900-6352-11eb-9e7b-dd123354e1c8.png)

![image](https://user-images.githubusercontent.com/5826484/106374584-a9abaa80-6352-11eb-87c6-78d34b5a215a.png)

I checked the host UNRAID and the container folder `/data` should be mapped to the appdate folder `/mnt/user/appdata/portainer`. I even manually created the artifactory folder but still get this error.

```bash
root@Tower:/mnt/user/appdata/portainer# ls -lasth
total 416K
404K -rw------- 1 root   root  404K Jan 30 23:20 portainer.db
   0 drwxrwxrwx 1 nobody users  146 Jan 30 22:36 ./
4.0K -rw-r--r-- 1 root   root   471 Jan 30 22:36 config.json
   0 drwxrwxrwx 1 root   root     0 Jan 30 22:02 artifactory/
   0 drwx------ 1 root   root     4 Jan 30 21:59 compose/
4.0K -rw------- 1 root   root   190 Jan 30 19:49 portainer.pub
4.0K -rw------- 1 root   root   227 Jan 30 19:49 portainer.key
   0 drwx------ 1 root   root     0 Jan 30 19:49 bin/
   0 drwx------ 1 root   root     0 Jan 30 19:49 tls/
   0 drwxrwxrwx 1 nobody users 1.2K Jan 30 19:49 ../
```

**Comment by frakman1** [comment, marked as answer]
UPDATE
---
The issue was due to the fact that I had run `docker swarm init` on the UNRAID host as part of an inital workaround for the original portainer that didn't support v3 of docker-compose scripts.
To undo that, i had to run `docker swarm leave --force`, restart portainer and create a new stack. Now it works!

![image](https://user-images.githubusercontent.com/5826484/106378616-4fbbdc80-6374-11eb-853a-ea74bb0848ac.png)

![image](https://user-images.githubusercontent.com/5826484/106378784-5dbe2d00-6375-11eb-84db-cab76941fc02.png)

Note that in order to launch the WebUI, you have to go into "Endpoint" on the left frame and select the "local" endpoint and set its Public IP address be that of your UNRAID server. Then, clicking on the "Published Ports" entry in the Stack view will open the WebUI correctly.

![image](https://user-images.githubusercontent.com/5826484/106378796-6f073980-6375-11eb-84bd-d902c298ab04.png)

---

The other problem was that in my `docker-compose.yml` file, I should have used the `/mnt/user/appdata/artifactory` (created manually) folder for my host volume location, otherwise, everything goes in the `/data` folder on the UNRAID server. 

Folder structure:

```bash
/mnt/user/appdata/artifactory
├── artifactory
└── nginx
```

New .yml file:

```yaml
version: '3'
services:
 artifactory:
   image: docker.bintray.io/jfrog/artifactory-oss:6.8.3
   user: "${UID}:${GID}"
   container_name: artifactory
   ports:
    - 6081:8081
   volumes:
    - /mnt/user/appdata/artifactory/artifactory:/var/opt/jfrog/artifactory
   environment:
    - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx2g -Xss256k -XX:+UseG1GC
   restart: always
   ulimits:
     nproc: 65535
     nofile:
       soft: 32000
       hard: 40000
 nginx:
   image: docker.bintray.io/jfrog/nginx-artifactory-pro:6.8.3
   container_name: nginx
   ports:
    - 680:80
    - 6443:443
   depends_on:
    - artifactory
   links:
    - artifactory
   volumes:
    - /mnt/user/appdata/artifactory/nginx:/var/opt/jfrog/nginx
   environment:
    - ART_BASE_URL=http://artifactory:8081/artifactory
    - SSL=true
   restart: always
   ulimits:
     nproc: 65535
     nofile:
       soft: 32000
       hard: 40000

```
